name: Tests

on:
  push:
    branches: [ "aperture" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "aperture" ]

# Builds images for target boards.
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22']
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go }}
      - name: Test Go
        run: make test
      - name: Lint Go
        run: make lint
